// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI4fH14-bINQgfzdoEb64RrccX2QGdlaY',
    appId: '1:285176901361:web:dbc04126b4dd1227cd8350',
    messagingSenderId: '285176901361',
    projectId: 'explorer-dz',
    authDomain: 'explorer-dz.firebaseapp.com',
    storageBucket: 'explorer-dz.firebasestorage.app',
    measurementId: 'G-LGDDBZ6184',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCNg4wwBwCasiqFkrdZ0HGJmS8BiU2h0M',
    appId: '1:285176901361:android:727b4a4449a29629cd8350',
    messagingSenderId: '285176901361',
    projectId: 'explorer-dz',
    storageBucket: 'explorer-dz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlYIlfynD8xdohkzLOJY36GJL35FVL4ZA',
    appId: '1:285176901361:ios:8fddb486dab78f4fcd8350',
    messagingSenderId: '285176901361',
    projectId: 'explorer-dz',
    storageBucket: 'explorer-dz.firebasestorage.app',
    iosBundleId: 'com.example.appPfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlYIlfynD8xdohkzLOJY36GJL35FVL4ZA',
    appId: '1:285176901361:ios:8fddb486dab78f4fcd8350',
    messagingSenderId: '285176901361',
    projectId: 'explorer-dz',
    storageBucket: 'explorer-dz.firebasestorage.app',
    iosBundleId: 'com.example.appPfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI4fH14-bINQgfzdoEb64RrccX2QGdlaY',
    appId: '1:285176901361:web:1500eddf08bd300acd8350',
    messagingSenderId: '285176901361',
    projectId: 'explorer-dz',
    authDomain: 'explorer-dz.firebaseapp.com',
    storageBucket: 'explorer-dz.firebasestorage.app',
    measurementId: 'G-GS8SGLLWL8',
  );
}
